---
# YAML documents begin with the document separator ---
# The minus in YAML this indicates a list item. The Playbook contains a list
# of plays, with each play being a dictionary

- name: 'loop with_subelements example playbook'

  # Target: where our play will run and options it will run with
  hosts: webservers

  # Task: the list of tasks that will be executed within the playbook
  tasks:       
     - name: Create user
       user:
         name: "{{ item.key }}"
         comment: "{{ item.value.full_name }}"
         state: present
       with_dict: 
         james:
           full_name: James Spurin

     - name: Create authorized key
       authorized_key:
         user: james
         key: "{{ item }}"
       with_file:
         - /root/.ssh/id_rsa.pub 
# Three dots indicate the end of a YAML document
...
